routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pais/ciudad/{id}', 'PaisCiudadController@getCiudad');
Route::get('/pais/ciudades/{pais}', 'PaisCiudadController@getCiudadPais');
Route::get('/pais', 'PaisCiudadController@getPais');

Route::get('/huesped/search', 'HuespedController@search')->name('huesped.search');
Route::get('/huesped/file/{id}/{tipo}', 'HuespedController@getFile');
Route::post('/huesped/add-new-contacto', 'HuespedController@addNewContacto');
Route::resource('/huesped', 'HuespedController');

// Pausas 
Route::get('/huesped/listar-pausas/{id_huesped}', 'PausaController@listarPausas');
Route::post('/huesped/guardar-pausas/{id_huesped}', 'PausaController@storePausa');

// Festivos y dias no festivos
Route::get('/huesped/listar-festivos/{id_huesped}', 'FestivosController@listarFestivos');
Route::post('/huesped/guardar-festivos/{id_huesped}', 'FestivosController@storeFestivos');

// Mail notificaciones internas
Route::get('/huesped/mail-notificaciones-internas/{id_huesped}', 'MailNotificacionesController@showMailNotificacion');
Route::post('/huesped/registrar-mail-notificaciones/{id_huesped}', 'MailNotificacionesController@insertarMailNotificacion');

// Notificaciones Internas
Route::post('/huesped/prueba-email-notificacion-smtp/{idEmail}', 'HuespedController@testCuentaNotificaciones');

// Proveedor Sms
Route::get('/huesped/proveedor-sms/{id}', 'ProveedorSmsController@ShowProveedorSms');
Route::get('/huesped/listar-proveedores-sms/{id_huesped}', 'ProveedorSmsController@showAllProveedorSms');
Route::post('/huesped/crear-proveedor-sms/{id_huesped}', 'ProveedorSmsController@storeProveedorSms');
Route::put('/huesped/actualizar-proveedor-sms/{id}', 'ProveedorSmsController@updateProveedorSms');
Route::delete('/huesped/eliminar-proveedor-sms/{id}', 'ProveedorSmsController@deleteProveedorSms');
Route::post('/huesped/prueba-proveedor-sms', 'ProveedorSmsController@pruebaEnviarSms');

// Seccion Cuentas de correo
Route::get('/huesped/cuenta-correo/{id}', 'CuentaCorreoController@showCuentaCorreo');
Route::get('/huesped/listar-cuentas-correo/{id}', 'CuentaCorreoController@showAllCuentaCorreo');
Route::post('/huesped/crear-cuenta-correo/{id}', 'CuentaCorreoController@storeCuentaCorreo')->name('canal.cuentaCorreo');
Route::put('/huesped/actualizar-cuenta-correo/{id}', 'CuentaCorreoController@updateCuentaCorreo');
Route::delete('/huesped/eliminar-cuenta-correo/{id}', 'CuentaCorreoController@deleteCuentaCorreo');
Route::post('/huesped/test-correo-send-mail-service', 'CuentaCorreoController@testSendMailService');
Route::post('/huesped/test-correo-in', 'CuentaCorreoController@testEntrada');

// Seccion troncales
Route::get('/huesped/estado-troncal/{id_huesped}', 'TroncalController@getEstadoTroncales');
Route::get('/huesped/listar-troncales/{id_huesped}', 'TroncalController@getTroncales');
Route::get('/huesped/troncal/{id_troncal}', 'TroncalController@getTroncal');
Route::post('/huesped/crear-troncal/{id_huesped}', 'TroncalController@storeTroncal');
Route::put('/huesped/actualizar-troncal/{id_troncal}', 'TroncalController@updateTroncal');
Route::delete('/huesped/eliminar-troncal/{id_troncal}', 'TroncalController@deleteTroncal');

// Seccion usuarios
Route::get('/huesped/listar-usuarios/{id_huesped}', 'UsuarioController@getUsuarios');
Route::get('/listar-usuarios-admin', 'UsuarioController@getUsuariosDyalogo');
Route::post('/huesped/asignar-usuario/{id_huesped}', 'UsuarioController@asignarUsuario');
Route::post('/huesped/crear-usuario/{id_huesped}', 'UsuarioController@storeUsuario');
Route::delete('/huesped/eliminar-usuario/{id_usuario}', 'UsuarioController@desvincularUsuario');

app/Models/Huesped.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Huesped extends Model
{
    /**
    * The database connection used by the model.
    *
    * @var string
    */
    protected $connection = 'general';

    /**
    * The database table used by the model.
    *
    * @var string
    */
    protected $table = 'huespedes';

    public $timestamps = false;

    /**
     * Get the contactos for the huesped.
    */
    public function contactos(){
        return $this->hasMany('App\Models\HuespedContacto', 'id_huesped', 'id');
    }

    public function pausas(){
        return $this->hasMany('App\Models\DyTipoDescanso', 'id_proyecto', 'id');
    }

    public function proyecto(){
        return $this->hasOne('App\Models\Dy_Proyectos', 'id_huesped', 'id');
    }

    public function mailNotificacion(){
        return $this->hasOne('App\Models\MailNotificacion', 'id_huesped', 'id');
    }

    public function troncales(){
        return $this->hasMany('App\Models\Troncal', 'id_proyecto', 'id');
    }

    // Query Scope
    public function scopeName($query, $name){
        if($name)
            return $query->where('nombre', 'LIKE', "%$name%");
    }
}

app/Http/Controllers/HuespedController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use Carbon\Carbon;
use App\Http\Requests\HuespedCreateRequest;
use App\Http\Requests\HuespedUpdateRequest;

use App\Models\Huesped;
use App\Models\HuespedContacto;
use App\Models\Dy_Proyectos;
use App\Models\DyTipoDescanso;
use App\Models\Proyect;
use App\User;
use App\Models\HuespedUsuario;
use App\Models\MailNotificacion;

class HuespedController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Busca un huesped en especifico
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request){
        // Verificar si la consulta es ajax
        if(!$request->ajax()){
            return redirect('/huesped'); 
        }

        $name = $request->texto;
        $huespedes = Huesped::orderBy('nombre', 'ASC')->name($name)->get();

        $data = [
            'code' => 200,
            'status' => 'success',
            'huespedes' => $huespedes
        ];

        return response()->json($data, $data['code']);
        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        
        $huespedes = Huesped::orderBy('nombre', 'ASC')->get();

        $paises = DB::connection('telefonia')
            ->table('dy_pais_ciudad')
            ->select('pais')
            ->groupBy('pais')
            ->get();

        $data = [
            'huespedes' => $huespedes,
            'paises' => $paises,
        ];
        
        return view('huesped.index', $data);
    }

    /**
     * Show the data for the given huesped.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){
        $huesped = Huesped::find($id)->load('contactos', 'proyecto', 'mailNotificacion', 'pausas', 'troncales');

        if($huesped){
            $data = [
                'code' => 200,
                'status' => 'success',
                'huesped' => $huesped
            ];
        }else{
            $data = [
                'code' => 404,
                'status' => 'error',
                'message' => 'No se pudo obtener los datos del huésped'
            ];
        }
        return response()->json($data, $data['code']);
    }

    /**
     * Store a new huesped.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HuespedCreateRequest $request){
        // Verificar si la consulta es ajax
        if(!$request->ajax()){
            return redirect('/huesped'); 
        }

        $con1 = DB::connection('general');
        $con2 = DB::connection('telefonia');
        $con3 = DB::connection('crm_sistema');
    
        $con1->beginTransaction();
        $con2->beginTransaction();
        $con3->beginTransaction();

        try {
            // Registro de dyalogo_general.huespedes
            $huesped = new Huesped();
            $huesped->nombre = $request->nombre;
            $huesped->notificar_pausas = ($request->notificar_pausas) ? 1 : 0;
            $huesped->notificar_sesiones = ($request->notificar_sesiones) ? 1 : 0;
            $huesped->notificar_incumplimientos = ($request->notificar_incumplimientos) ? 1 : 0;
            $huesped->emails_notificar_pausas = $request->emails_notificar_pausas;
            $huesped->emails_notificar_sesiones = $request->emails_notificar_sesiones;
            $huesped->emails_notificar_incumplimientos = $request->emails_notificar_incumplimientos;
            $huesped->razon_social = $request->razon_social;
            $huesped->nit = $request->nit;
            $huesped->id_pais_ciudad = $request->ciudad;
            $huesped->direccion = $request->direccion;
            $huesped->telefono1 = $request->telefono1;
            $huesped->telefono2 = $request->telefono2;
            $huesped->telefono3 = $request->telefono3;
            $huesped->malla_turno_requerida = ($request->mallaTurnoRequerida) ? 1 : 0;
            $huesped->malla_turno_horario_por_defecto = ($request->mallaTurnoHorarioDefecto) ? 1 : 0;
            $huesped->hora_entrada_por_defecto = $request->horaEntrada;
            $huesped->hora_salida_por_defecto = $request->horaSalida;
            $huesped->cantidad_max_supervisores = $request->cantidadMaximaSupervisores;
            $huesped->cantidad_max_bo = $request->cantidadMaximaBackoffice;
            $huesped->mensaje = $request->mensajeActual;
            $huesped->foto_usuario_obligatoria = ($request->fotoUsuarioObligatoria) ? 1 : 0;

            $huesped->save();

            // Registro de dyalogo_general.huespedes_contactos
            for ($i=0; $i < count($request->contacto_nombre) ; $i++) { 
                $contacto = new HuespedContacto();
                $contacto->id_huesped = $huesped->id;
                $contacto->nombre = $request->contacto_nombre[$i];
                $contacto->email = $request->contacto_email[$i];
                $contacto->tipo = $request->contacto_tipo[$i];
                $contacto->telefono1 = $request->contacto_telefono1[$i];
                $contacto->telefono2 = $request->contacto_telefono2[$i];
                $contacto->save();
            }               
            
            // Replicacion en otras tablas - dyalogo_telefonia.dy_proyectos
            $dyProyecto = new Dy_Proyectos();
            $dyProyecto->id = $huesped->id;
            $dyProyecto->nombre = $huesped->nombre;
            $dyProyecto->fecha_inicial = Carbon::now();
            $dyProyecto->fecha_final = Carbon::now()->addMonths(6);
            $dyProyecto->cantidad_max_agentes_simultaneos = $request->cantidadMaxAgentesSimultaneos;
            $dyProyecto->id_huesped = $huesped->id;
            $dyProyecto->save();

            // Replicacion en otras tablas - DYALOGOCRM_SISTEMA.PROYECT
            $proyect = new Proyect();
            $proyect->PROYEC_ConsInte__b = $huesped->id;
            $proyect->PROYEC_NomProyec_b = $huesped->nombre;
            $proyect->PROYEC_FechCrea__b = Carbon::now();
            $proyect->PROYEC_UsuaCrea__b = Auth::user()->USUARI_ConsInte__b;
            $proyect->save();

            $mailNotificacion = MailNotificacion::updateOrCreate(
                ['id_huesped'=> $huesped->id],
                [
                    'servidor_smtp'=> $request->notificacion_servidor_smtp,
                    'dominio' =>  $request->notificacion_dominio,
                    'puerto' => $request->notificacion_puerto,
                    'usuario' => $request->notificacion_usuario,
                    'password' => $request->notificacion_password,
                    'ttls' => ($request->notificacion_ttls) ? 1 : 0,
                    'auth' => ($request->notificacion_auth) ? 1 : 0,
                ]
            );

            // Asignacion de usuario_huesped predeterminado
            $huespedUsuari1 = new HuespedUsuario();
            $huespedUsuari1->id_huesped = $huesped->id;
            $huespedUsuari1->id_usuario = 41;
            $huespedUsuari1->save();

            // Obtener el cogido con el valor maximo de la tabla dy_tipos_descanso
            $last_codigo_descanso = DB::connection('telefonia')
                ->table('dy_tipos_descanso')
                ->max(DB::raw('CAST(codigo AS UNSIGNED)'));

            // Creacion de las pausas por defecto predeterminadas
            // Con horario
            $arrPausa1 = ['tipo' => $huesped->nombre.' - Break mañana', 'codigo'=> $last_codigo_descanso + 1, 'descanso'=> true,  'id_proyecto'=> $huesped->id, 'duracion_maxima' => null, 'cantidad_maxima_evento_dia'=> null, 'hora_inicial_por_defecto'=> '10:00:00', 'hora_final_por_defecto'=> '10:15:00', 'tipo_pausa'=> true];
            $arrPausa2 = ['tipo' => $huesped->nombre.' - Almuerzo',     'codigo'=> $last_codigo_descanso + 2, 'descanso'=> true,  'id_proyecto'=> $huesped->id, 'duracion_maxima' => null, 'cantidad_maxima_evento_dia'=> null, 'hora_inicial_por_defecto'=> '12:30:00', 'hora_final_por_defecto'=> '13:30:00', 'tipo_pausa'=> true];
            $arrPausa3 = ['tipo' => $huesped->nombre.' - Break tarde',  'codigo'=> $last_codigo_descanso + 3, 'descanso'=> true,  'id_proyecto'=> $huesped->id, 'duracion_maxima' => null, 'cantidad_maxima_evento_dia'=> null, 'hora_inicial_por_defecto'=> '16:00:00', 'hora_final_por_defecto'=> '16:15:00', 'tipo_pausa'=> true];
            // Sin horario
            $arrPausa4 = ['tipo' => $huesped->nombre.' - Reunión',      'codigo'=> $last_codigo_descanso + 4, 'descanso'=> false, 'id_proyecto'=> $huesped->id, 'duracion_maxima' => 480,    'cantidad_maxima_evento_dia'=> 3,    'hora_inicial_por_defecto'=> null,       'hora_final_por_defecto'=> null,       'tipo_pausa'=> false];
            $arrPausa5 = ['tipo' => $huesped->nombre.' - Capacitación', 'codigo'=> $last_codigo_descanso + 5, 'descanso'=> false, 'id_proyecto'=> $huesped->id, 'duracion_maxima' => 480,    'cantidad_maxima_evento_dia'=> 3,    'hora_inicial_por_defecto'=> null,       'hora_final_por_defecto'=> null,       'tipo_pausa'=> false];
            $arrPausa6 = ['tipo' => $huesped->nombre.' - Gestión',      'codigo'=> $last_codigo_descanso + 6, 'descanso'=> false, 'id_proyecto'=> $huesped->id, 'duracion_maxima' => 480,    'cantidad_maxima_evento_dia'=> 3,    'hora_inicial_por_defecto'=> null,       'hora_final_por_defecto'=> null,       'tipo_pausa'=> false];
            $arrPausa7 = ['tipo' => $huesped->nombre.' - Baño',         'codigo'=> $last_codigo_descanso + 7, 'descanso'=> true,  'id_proyecto'=> $huesped->id, 'duracion_maxima' => 15,   'cantidad_maxima_evento_dia'=> 2,    'hora_inicial_por_defecto'=> null,       'hora_final_por_defecto'=> null,       'tipo_pausa'=> false]; 
            
            $pausa1 = DyTipoDescanso::crearNuevaPausa($arrPausa1);

resources/views/huesped/forms/archivos.blade.php
<table class="table"> 
    <tr>
        <th>Tipo de archivo</th>
        <th>Subir nuevo archivo <small class="text-muted">(Peso máximo por archivo: 3MB)</small></th>
        <th>Descargar</th>
    </tr>
    <tr>
        <th>Cámara de comercio</th>
        <td>
            <div class="input-group input-group-sm">
                <input type="file" class="form-control" name="camara_comercio" form="form-huesped">
            </div>               
        </td>
        <td class="text-center">
            <a href="#" class="camara_comercio doc btn btn-success btn-sm " target="_blank"> <i class="fa fa-download"></i> </a>
        </td>
    </tr>

    <tr>
        <th>RUT</th>
        <td> 
            <div class="input-group input-group-sm">
                <input type="file" class="form-control" name="rut" form="form-huesped">
            </div>               
        </td>
        <td class="text-center">
            <a href="#" class="rut doc btn btn-success btn-sm" target="_blank"><i class="fa fa-download"></i></a>
        </td>
    </tr>

    <tr>
        <th>Certificación bancaría</th>
        <td>    
            <div class="input-group input-group-sm">
                <input type="file" class="form-control" name="certificacion_bancaria" form="form-huesped">
            </div>              
        </td>
        <td class="text-center">
            <a href="#" class="certificacion_bancaria doc btn btn-success btn-sm" target="_blank"><i class="fa fa-download"></i></a>
        </td>
    </tr>

    <tr>
        <th>Orden de compra</th>
        <td>    
            <div class="input-group input-group-sm">
                <input type="file" class="form-control" name="orden_compra" form="form-huesped">
            </div>
        </td>
        <td class="text-center">
            <a href="#" class="orden_compra doc btn btn-success btn-sm" target="_blank"><i class="fa fa-download"></i></a>
        </td>
    </tr>

    <tr>
        <th>Alcances</th>
        <td>    
            <div class="input-group input-group-sm">
                <input type="file" class="form-control" name="alcances" form="form-huesped">
            </div>
        </td>
        <td class="text-center">
            <a href="#" class="alcances doc btn btn-success btn-sm" target="_blank"><i class="fa fa-download"></i></a>
        </td>
    </tr>
</table>

resources/views/huesped/forms/contacto.blade.php
<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Tipo</th>
            <th>Telefono 1</th>
            <th>Telefono 2</th>
        </tr>
    </thead>
    <tbody>
        <tr class="linea-contacto">
            <td>
                <input type="text" class="form-control" name="contacto_nombre[]" placeholder="Ingresa el nombre" required form="form-huesped">
            </td>
            <td>
                <input type="email" class="form-control" name="contacto_email[]" placeholder="Ingresa el email" form="form-huesped">
            </td>
            <td>
                <select name="contacto_tipo[]" class="form-control" form="form-huesped">
                    <option value="T">Tecnico</option>
                    <option value="P">Pagos</option>
                    <option value="F">Funcional</option>
                </select>
            </td>
            <td>
                <input type="tel" class="form-control" name="contacto_telefono1[]" placeholder="Ingresa el numero de teléfono" form="form-huesped">
            </td>
            <td>
                <input type="tel" class="form-control" name="contacto_telefono2[]" placeholder="Ingresa el numero de teléfono" form="form-huesped">
            </td>
        </tr>
    </tbody>
</table>

resources/views/huesped/forms/edit.blade.php
<form action="huesped" id="form-huesped" class="edit" method="POST">
    @csrf
    <div class="">
        <input type="hidden" name="id_huesped" id="id_huesped" value="{{ $huespedes->first()->id }}" form="form-huesped">
        <h3>Información Principal</h3>
        <div class="form-group row">
            <div class="col-md-6">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresa el nombre" value="{{ $huespedes->first()->nombre }}" form="form-huesped">
            </div>
        
            <div class="col-md-3">
                <label for="razon_social">Razón Social</label>
                <input type="text" class="form-control" id="razon_social" name="razon_social" placeholder="Ingresa la razón social" value="{{ $huespedes->first()->razon_social }}" form="form-huesped">
            </div>
            <div class="col-md-3">
                <label for="nit">NIT</label>
                <input type="text" class="form-control" id="nit" name="nit" placeholder="Ingresa el NIT" value="{{ $huespedes->first()->nit }}" form="form-huesped">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                <label for="pais">Pais</label>
                <select name="pais" id="pais" class="form-control" form="form-huesped">
                    <option value=''>Seleccionar</option>
                    @foreach ($paises as $pais)
                        <option value="{{ $pais->pais }}">{{ $pais->pais }}</option>
                    @endforeach
                </select>
            </div>

            <div class="col-md-3">
                <label for="ciudad">Ciudad</label>
                <select name="ciudad" id="ciudad" class="form-control" form="form-huesped">
                    <option value=''>Seleccionar</option>
                    <option value="{{ $huespedes->first()->id_pais_ciudad }}">{{ $huespedes->first()->id_pais_ciudad }}</option>
                </select>
            </div>

            <div class="col-md-6">
                <label for="direccion">Dirección</label>
                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingresa la Dirección" value="{{ $huespedes->first()->direccion }}" form="form-huesped">
            </div>
        </div>
        
        <div class="form-group row">
            <div class="col-md-4">
                <label for="telefono1">Teléfono 1</label>
                <input type="tel" class="form-control" id="telefono1" name="telefono1" placeholder="Ingresa el numero de teléfono" value="{{ $huespedes->first()->telefono1 }}" form="form-huesped">
            </div>
            <div class="col-md-4">
                <label for="telefono2">Teléfono 2 (Opcional)</label>
                <input type="tel" class="form-control" id="telefono2" name="telefono2" placeholder="Ingresa el numero de teléfono" value="{{ $huespedes->first()->telefono2 }}" form="form-huesped">
            </div>
            <div class="col-md-4">
                <label for="telefono3">Teléfono 3 (Opcional)</label>
                <input type="tel" class="form-control" id="telefono3" name="telefono3" placeholder="Ingresa el numero de teléfono" value="{{ $huespedes->first()->telefono3 }}" form="form-huesped">
            </div>                        
        </div>    

        <h3 class="text-aqua">Notificaciones</h3>
        <div class="form-group row">
            <div class="col-md-4">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="notificar_pausas" name="notificar_pausas" @if($huespedes->first()->notificar_pausas) checked @endif form="form-huesped">
                        Notificar Pausas
                    </label>
                </div>
            </div>
            <div class="col-md-4">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="notificar_sesiones" name="notificar_sesiones" @if($huespedes->first()->notificar_sesiones) checked @endif form="form-huesped">
                        Notificar Sesiones
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
                <label for="emails_notificaciones">Emails para notificaciones</label>
                <input type="text" class="form-control" id="emails_notificaciones" name="emails_notificaciones" placeholder="Ingresa los emails" value="{{ $huespedes->first()->emails_notificaciones }}" form="form-huesped">

            </div>
        </div>

    </div>
    <button type="submit" class="btn btn-primary pull-right save">Guardar cambios</button>

</form>

resources/views/huesped/forms/huesped_form.blade.php
<h3 class="title text-aqua">Registrar huésped</h3>

<form action="{{ route('huesped.store') }}" method="POST" id="form-huesped" class="" enctype="multipart/form-data">
    @csrf
    
    <h4 class="text-aqua">Datos del huésped</h4>
    <input type="hidden" name="id" id="id">
    <div class="form-group row">
        <div class="col-md-6">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresa el nombre">
        </div>

        <div class="col-md-6">
            <label for="direccion">Dirección</label>
            <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingresa la Dirección">
        </div>
    
        
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <label for="razon_social">Razón Social</label>
            <input type="text" class="form-control" id="razon_social" name="razon_social" placeholder="Ingresa la razón social"">
        </div>
        <div class="col-md-3">
            <label for="nit">NIT</label>
            <input type="text" class="form-control" id="nit" name="nit" placeholder="Ingresa el NIT">
        </div>

        <div class="col-md-3">
            <label for="pais">Pais</label>
            <select name="pais" id="pais" class="form-control">
                <option value=''>Seleccionar</option>
                @foreach ($paises as $pais)
                    <option value="{{ $pais->pais }}">{{ $pais->pais }}</option>
                @endforeach
            </select>
        </div>

        <div class="col-md-3">
            <label for="ciudad">Ciudad</label>
            <select name="ciudad" id="ciudad" class="form-control">
                <option value=''>Seleccionar</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <label for="telefono1">Teléfono 1</label>
            <input type="tel" class="form-control" id="telefono1" name="telefono1" placeholder="Ingresa el numero de teléfono">
        </div>
        <div class="col-md-3">
            <label for="telefono2">Teléfono 2 (Opcional)</label>
            <input type="tel" class="form-control" id="telefono2" name="telefono2" placeholder="Ingresa el numero de teléfono">
        </div>
        <div class="col-md-3">
            <label for="telefono3">Teléfono 3 (Opcional)</label>
            <input type="tel" class="form-control" id="telefono3" name="telefono3" placeholder="Ingresa el numero de teléfono">
        </div>                        
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="fotoUsuarioObligatoria" name="fotoUsuarioObligatoria" form="form-huesped" checked>
                    Foto de usuarios obligatoria
                </label>
            </div>
        </div>
    </div>
</form>

    @include('huesped.secciones.cantidadesAutorizadas')
    
    @include('huesped.secciones.pausas')

    @include('huesped.secciones.mallaTurnos')

    @include('huesped.secciones.festivos')

    @include('huesped.secciones.cuentasCorreo')
                                
    @include('huesped.secciones.proveedoresSms')

    @include('huesped.secciones.troncales')

    @include('huesped.secciones.notificaciones')
    
    @include('huesped.secciones.mensajeActual')

    @include('huesped.secciones.usuarios')

    @include('huesped.secciones.contactos')

    @include('huesped.secciones.archivos')

@include('huesped.modals.pruebaNotificacionesMailSmsModal')